;;; johnson-bgl-test.el --- Tests for johnson-bgl -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Free Software Foundation, Inc.

;; Author: Pablo Stafforini <pablostafforini@gmail.com>

;; This file is NOT part of GNU Emacs.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; ERT tests for the johnson-bgl format backend module.
;; Fixtures are generated by test/generate-bgl-fixture.py.

;;; Code:

(require 'ert)
(require 'johnson-bgl)
(require 'johnson)

;;;; Helpers

(defvar johnson-bgl-test--fixtures-dir
  (expand-file-name "fixtures/"
                    (file-name-directory (or load-file-name
                                             buffer-file-name
                                             default-directory)))
  "Path to the test fixtures directory.")

(defun johnson-bgl-test--fixture (name)
  "Return the full path to the fixture file NAME."
  (expand-file-name name johnson-bgl-test--fixtures-dir))

(defun johnson-bgl-test--cleanup ()
  "Clean up BGL caches."
  (johnson-bgl-clear-caches))

;;;; Binary helpers

(ert-deftest johnson-bgl-test-u16be ()
  "Reads 16-bit big-endian integers correctly."
  (let ((data (string #x00 #x05)))
    (should (= (johnson-binary-u16be data 0) 5)))
  (let ((data (string #x01 #x00)))
    (should (= (johnson-binary-u16be data 0) 256))))

(ert-deftest johnson-bgl-test-u32be ()
  "Reads 32-bit big-endian integers correctly."
  (let ((data (string #x00 #x00 #x00 #x01)))
    (should (= (johnson-binary-u32be data 0) 1)))
  (let ((data (string #x00 #x01 #x00 #x00)))
    (should (= (johnson-binary-u32be data 0) 65536))))

;;;; Block header parsing

(ert-deftest johnson-bgl-test-parse-block-header-inline-length ()
  "Parses block header with inline length (nibble >= 4)."
  ;; Type 3, length nibble = 5 (meaning length = 1): byte = 0x53
  (let ((data (string #x53 #xAA)))
    (let ((result (johnson-bgl--parse-block-header data 0)))
      (should (= (nth 0 result) 3))    ; type
      (should (= (nth 1 result) 1))    ; length = 5 - 4
      (should (= (nth 2 result) 1))))) ; next-pos

(ert-deftest johnson-bgl-test-parse-block-header-extra-bytes ()
  "Parses block header with extra length bytes (nibble < 4)."
  ;; Type 1, nibble = 0 => 1 extra byte for length.
  ;; byte = 0x01, next byte = 0x0A => length = 10
  (let ((data (string #x01 #x0A #xFF)))
    (let ((result (johnson-bgl--parse-block-header data 0)))
      (should (= (nth 0 result) 1))    ; type
      (should (= (nth 1 result) 10))   ; length
      (should (= (nth 2 result) 2))))) ; next-pos past header

;;;; Format detection

(ert-deftest johnson-bgl-test-detect-accepts-bgl ()
  "Accepts a valid BGL file."
  (should (johnson-bgl-detect
           (johnson-bgl-test--fixture "test-bgl.bgl"))))

(ert-deftest johnson-bgl-test-detect-rejects-non-bgl ()
  "Rejects a file that is not a BGL file."
  (should-not (johnson-bgl-detect
               (johnson-bgl-test--fixture "test-mdict.mdx"))))

(ert-deftest johnson-bgl-test-detect-rejects-wrong-extension ()
  "Rejects a file without .bgl extension."
  (should-not (johnson-bgl-detect
               (johnson-bgl-test--fixture "test-stardict.ifo"))))

;;;; Metadata parsing

(ert-deftest johnson-bgl-test-parse-metadata ()
  "Parses metadata from a BGL file."
  (johnson-bgl-test--cleanup)
  (let ((meta (johnson-bgl-parse-metadata
               (johnson-bgl-test--fixture "test-bgl.bgl"))))
    (should (equal (plist-get meta :name) "Test BGL Dictionary"))
    (should (equal (plist-get meta :source-lang) "English"))
    (should (equal (plist-get meta :target-lang) "English"))))

;;;; Index building

(ert-deftest johnson-bgl-test-build-index ()
  "Builds index from BGL fixture."
  (johnson-bgl-test--cleanup)
  (let ((entries nil))
    (johnson-bgl-build-index
     (johnson-bgl-test--fixture "test-bgl.bgl")
     (lambda (hw offset size)
       (push (list hw offset size) entries)))
    (should (= (length entries) 3))
    (let ((headwords (mapcar #'car entries)))
      (should (member "apple" headwords))
      (should (member "cat" headwords))
      (should (member "hello" headwords)))))

(ert-deftest johnson-bgl-test-build-index-offsets ()
  "Index entries have valid byte offsets and sizes."
  (johnson-bgl-test--cleanup)
  (let ((entries nil))
    (johnson-bgl-build-index
     (johnson-bgl-test--fixture "test-bgl.bgl")
     (lambda (hw offset size)
       (push (list hw offset size) entries)))
    ;; All offsets should be positive.
    (should (cl-every (lambda (e) (> (nth 1 e) 0)) entries))
    ;; All sizes should be positive.
    (should (cl-every (lambda (e) (> (nth 2 e) 0)) entries))))

;;;; Entry retrieval

(ert-deftest johnson-bgl-test-retrieve-entry ()
  "Retrieves an entry from BGL fixture."
  (johnson-bgl-test--cleanup)
  (let ((entries nil))
    (johnson-bgl-build-index
     (johnson-bgl-test--fixture "test-bgl.bgl")
     (lambda (hw offset size)
       (push (list hw offset size) entries)))
    (let* ((apple-entry (cl-find "apple" entries :key #'car :test #'equal))
           (text (johnson-bgl-retrieve-entry
                  (johnson-bgl-test--fixture "test-bgl.bgl")
                  (nth 1 apple-entry) (nth 2 apple-entry))))
      (should (stringp text))
      (should (string-match-p "round fruit" text)))))

(ert-deftest johnson-bgl-test-retrieve-all-entries ()
  "Retrieves all entries and verifies content."
  (johnson-bgl-test--cleanup)
  (let ((entries nil))
    (johnson-bgl-build-index
     (johnson-bgl-test--fixture "test-bgl.bgl")
     (lambda (hw offset size)
       (push (list hw offset size) entries)))
    (let* ((cat-entry (cl-find "cat" entries :key #'car :test #'equal))
           (text (johnson-bgl-retrieve-entry
                  (johnson-bgl-test--fixture "test-bgl.bgl")
                  (nth 1 cat-entry) (nth 2 cat-entry))))
      (should (string-match-p "feline" text)))
    (let* ((hello-entry (cl-find "hello" entries :key #'car :test #'equal))
           (text (johnson-bgl-retrieve-entry
                  (johnson-bgl-test--fixture "test-bgl.bgl")
                  (nth 1 hello-entry) (nth 2 hello-entry))))
      (should (string-match-p "greeting" text)))))

;;;; Rendering

(ert-deftest johnson-bgl-test-render-html ()
  "Renders HTML entry with text properties."
  (johnson-bgl-test--cleanup)
  (let ((entries nil))
    (johnson-bgl-build-index
     (johnson-bgl-test--fixture "test-bgl.bgl")
     (lambda (hw offset size)
       (push (list hw offset size) entries)))
    (let* ((apple-entry (cl-find "apple" entries :key #'car :test #'equal))
           (data (johnson-bgl-retrieve-entry
                  (johnson-bgl-test--fixture "test-bgl.bgl")
                  (nth 1 apple-entry) (nth 2 apple-entry))))
      (with-temp-buffer
        (johnson-bgl-render-entry data)
        (let ((text (buffer-substring-no-properties (point-min) (point-max))))
          ;; Tags should be removed.
          (should-not (string-match-p "<b>" text))
          (should (string-match-p "apple" text))
          (should (string-match-p "round fruit" text)))
        ;; Bold face should be applied.
        (let ((pos (text-property-any (point-min) (point-max)
                                      'face 'johnson-bold-face)))
          (should pos))))))

(ert-deftest johnson-bgl-test-render-removes-tags ()
  "All HTML tags are removed from rendered output."
  (johnson-bgl-test--cleanup)
  (let ((entries nil))
    (johnson-bgl-build-index
     (johnson-bgl-test--fixture "test-bgl.bgl")
     (lambda (hw offset size)
       (push (list hw offset size) entries)))
    (let* ((cat-entry (cl-find "cat" entries :key #'car :test #'equal))
           (data (johnson-bgl-retrieve-entry
                  (johnson-bgl-test--fixture "test-bgl.bgl")
                  (nth 1 cat-entry) (nth 2 cat-entry))))
      (with-temp-buffer
        (johnson-bgl-render-entry data)
        (let ((text (buffer-substring-no-properties (point-min) (point-max))))
          (should-not (string-match-p "<" text))
          (should-not (string-match-p ">" text)))))))

;;;; Control code stripping

(ert-deftest johnson-bgl-test-strip-control-codes ()
  "Strips BGL control codes from raw data."
  ;; 0x14 + 0x02 + POS byte should be removed.
  (let* ((raw (concat "hello" (unibyte-string #x14 #x02 #x05) " world"))
         (result (johnson-bgl--strip-control-codes raw)))
    (should (equal (decode-coding-string result 'utf-8) "hello world")))
  ;; 0x0A should become newline.
  (let* ((raw (concat "line1" (unibyte-string #x0A) "line2"))
         (result (johnson-bgl--strip-control-codes raw)))
    (should (equal (decode-coding-string result 'utf-8) "line1\nline2")))
  ;; 0x1E / 0x1F resource markers should be removed.
  (let* ((raw (concat "text" (unibyte-string #x1E) "more"))
         (result (johnson-bgl--strip-control-codes raw)))
    (should (equal (decode-coding-string result 'utf-8) "textmore"))))

;;;; Full integration

(ert-deftest johnson-bgl-test-full-integration ()
  "Full round-trip: detect, parse metadata, build index, retrieve, render."
  (johnson-bgl-test--cleanup)
  (let* ((path (johnson-bgl-test--fixture "test-bgl.bgl")))
    ;; 1. Detect.
    (should (johnson-bgl-detect path))
    ;; 2. Parse metadata.
    (let ((meta (johnson-bgl-parse-metadata path)))
      (should (equal (plist-get meta :name) "Test BGL Dictionary"))
      (should (equal (plist-get meta :source-lang) "English"))
      (should (equal (plist-get meta :target-lang) "English")))
    ;; 3. Build index.
    (let ((entries nil))
      (johnson-bgl-build-index path
                                (lambda (hw offset size)
                                  (push (list hw offset size) entries)))
      (should (>= (length entries) 3))
      ;; 4. Retrieve and render "apple".
      (let* ((apple-entry (cl-find "apple" entries :key #'car :test #'equal)))
        (should apple-entry)
        (let ((data (johnson-bgl-retrieve-entry
                     path (nth 1 apple-entry) (nth 2 apple-entry))))
          (with-temp-buffer
            (johnson-bgl-render-entry data)
            (let ((text (buffer-substring-no-properties
                         (point-min) (point-max))))
              (should (string-match-p "round fruit" text)))))))))

(ert-deftest johnson-bgl-test-full-integration-all-entries ()
  "Full round-trip: all entries from BGL fixture."
  (johnson-bgl-test--cleanup)
  (let* ((path (johnson-bgl-test--fixture "test-bgl.bgl"))
         (entries nil))
    (johnson-bgl-build-index path
                              (lambda (hw offset size)
                                (push (list hw offset size) entries)))
    ;; Retrieve and render every entry.
    (dolist (entry entries)
      (let ((data (johnson-bgl-retrieve-entry
                   path (nth 1 entry) (nth 2 entry))))
        (should (stringp data))
        (should (> (length data) 0))
        (with-temp-buffer
          (johnson-bgl-render-entry data)
          (let ((text (buffer-substring-no-properties
                       (point-min) (point-max))))
            ;; No HTML tags remaining.
            (should-not (string-match-p "<b>" text))))))))

(provide 'johnson-bgl-test)
;;; johnson-bgl-test.el ends here
