;;; johnson-mdict-test.el --- Tests for johnson-mdict -*- lexical-binding: t; -*-

;;; Commentary:

;; ERT tests for the johnson-mdict format backend module.
;; Fixtures are generated by test/generate-mdict-fixtures.py.

;;; Code:

(require 'ert)
(require 'johnson-mdict)
(require 'johnson)

;;;; Helpers

(defvar johnson-mdict-test--fixtures-dir
  (expand-file-name "fixtures/"
                    (file-name-directory (or load-file-name
                                             buffer-file-name
                                             default-directory)))
  "Path to the test fixtures directory.")

(defun johnson-mdict-test--fixture (name)
  "Return the full path to the fixture file NAME."
  (expand-file-name name johnson-mdict-test--fixtures-dir))

(defun johnson-mdict-test--cleanup ()
  "Clean up MDict caches."
  (johnson-mdict-clear-caches))

;;;; Header parsing

(ert-deftest johnson-mdict-test-parse-header ()
  "Parses MDict header correctly."
  (johnson-mdict-test--cleanup)
  (let ((header (johnson-mdict--parse-header
                 (johnson-mdict-test--fixture "test-mdict.mdx"))))
    (should (= (plist-get header :version) 2.0))
    (should (eq (plist-get header :encoding) 'utf-8))
    (should (= (plist-get header :encrypted) 0))
    (should (equal (plist-get header :title) "Test MDict Dictionary"))
    (should (= (plist-get header :num-width) 8))
    (should (> (plist-get header :header-end) 0))))

(ert-deftest johnson-mdict-test-parse-header-encrypted ()
  "Parses encrypted MDict header correctly."
  (johnson-mdict-test--cleanup)
  (let ((header (johnson-mdict--parse-header
                 (johnson-mdict-test--fixture "test-mdict-encrypted.mdx"))))
    (should (= (plist-get header :encrypted) 2))
    (should (equal (plist-get header :title) "Test MDict Encrypted"))))

;;;; Format detection

(ert-deftest johnson-mdict-test-detect-accepts-mdx ()
  "Accepts a valid MDict .mdx file."
  (should (johnson-mdict-detect
           (johnson-mdict-test--fixture "test-mdict.mdx"))))

(ert-deftest johnson-mdict-test-detect-rejects-non-mdx ()
  "Rejects a file that is not an MDict .mdx file."
  (should-not (johnson-mdict-detect
               (johnson-mdict-test--fixture "test-stardict.ifo"))))

;;;; Metadata parsing

(ert-deftest johnson-mdict-test-parse-metadata ()
  "Parses metadata from an MDict file."
  (johnson-mdict-test--cleanup)
  (let ((meta (johnson-mdict-parse-metadata
               (johnson-mdict-test--fixture "test-mdict.mdx"))))
    (should (equal (plist-get meta :name) "Test MDict Dictionary"))))

;;;; Block decompression

(ert-deftest johnson-mdict-test-decompress-zlib ()
  "Decompresses a zlib-compressed block."
  (let* ((original (encode-coding-string "Hello, world!" 'utf-8))
         ;; Pre-computed zlib.compress(b"Hello, world!").
         (compressed (string #x78 #x9c #xf3 #x48 #xcd #xc9 #xc9 #xd7
                             #x51 #x28 #xcf #x2f #xca #x49 #x51 #x04
                             #x00 #x20 #x5e #x04 #x8a))
         ;; Build MDict block: comp-type(4) + checksum(4) + compressed-data.
         (block (concat (string #x02 #x00 #x00 #x00
                                #x00 #x00 #x00 #x00)
                        compressed))
         (result (johnson-mdict--decompress-block block)))
    (should (equal result original))))

(ert-deftest johnson-mdict-test-decompress-plain ()
  "Decompresses an uncompressed block (passthrough)."
  (let* ((original (encode-coding-string "Plain data." 'utf-8))
         (block (concat (string #x00 #x00 #x00 #x00
                                #x00 #x00 #x00 #x00)
                        original))
         (result (johnson-mdict--decompress-block block)))
    (should (equal result original))))

(ert-deftest johnson-mdict-test-decompress-lzo-error ()
  "Signals error for LZO compression."
  (let ((block (string #x01 #x00 #x00 #x00
                       #x00 #x00 #x00 #x00)))
    (should-error (johnson-mdict--decompress-block block)
                  :type 'error)))

;;;; Keyword section parsing

(ert-deftest johnson-mdict-test-parse-keywords ()
  "Parses keyword section from unencrypted fixture."
  (johnson-mdict-test--cleanup)
  (let ((keywords (johnson-mdict--parse-keyword-section
                   (johnson-mdict-test--fixture "test-mdict.mdx"))))
    (should (= (length keywords) 3))
    (let ((headwords (cl-loop for entry across keywords
                              collect (car entry))))
      (should (member "apple" headwords))
      (should (member "cat" headwords))
      (should (member "hello" headwords)))))

(ert-deftest johnson-mdict-test-parse-keywords-encrypted ()
  "Parses keyword section from encrypted fixture."
  (johnson-mdict-test--cleanup)
  (let ((keywords (johnson-mdict--parse-keyword-section
                   (johnson-mdict-test--fixture "test-mdict-encrypted.mdx"))))
    (should (= (length keywords) 3))
    (let ((headwords (cl-loop for entry across keywords
                              collect (car entry))))
      (should (member "apple" headwords))
      (should (member "cat" headwords))
      (should (member "hello" headwords)))))

;;;; Record retrieval

(ert-deftest johnson-mdict-test-retrieve-entry ()
  "Retrieves entries from unencrypted fixture."
  (johnson-mdict-test--cleanup)
  (let* ((path (johnson-mdict-test--fixture "test-mdict.mdx"))
         (keywords (johnson-mdict--parse-keyword-section path))
         (apple-entry (cl-find "apple" keywords
                               :key #'car :test #'equal)))
    (should apple-entry)
    (let ((raw (johnson-mdict-retrieve-entry path (cdr apple-entry) 0)))
      (let ((text (decode-coding-string raw 'utf-8)))
        (should (string-match-p "round fruit" text))))))

(ert-deftest johnson-mdict-test-retrieve-all-entries ()
  "Retrieves all entries and verifies content."
  (johnson-mdict-test--cleanup)
  (let* ((path (johnson-mdict-test--fixture "test-mdict.mdx"))
         (keywords (johnson-mdict--parse-keyword-section path)))
    (let* ((cat-entry (cl-find "cat" keywords :key #'car :test #'equal))
           (raw (johnson-mdict-retrieve-entry path (cdr cat-entry) 0))
           (text (decode-coding-string raw 'utf-8)))
      (should (string-match-p "feline" text)))
    (let* ((hello-entry (cl-find "hello" keywords :key #'car :test #'equal))
           (raw (johnson-mdict-retrieve-entry path (cdr hello-entry) 0))
           (text (decode-coding-string raw 'utf-8)))
      (should (string-match-p "greeting" text)))))

(ert-deftest johnson-mdict-test-retrieve-encrypted ()
  "Retrieves entries from encrypted fixture."
  (johnson-mdict-test--cleanup)
  (let* ((path (johnson-mdict-test--fixture "test-mdict-encrypted.mdx"))
         (keywords (johnson-mdict--parse-keyword-section path))
         (apple-entry (cl-find "apple" keywords :key #'car :test #'equal)))
    (let ((raw (johnson-mdict-retrieve-entry path (cdr apple-entry) 0)))
      (let ((text (decode-coding-string raw 'utf-8)))
        (should (string-match-p "round fruit" text))))))

;;;; Rendering

(ert-deftest johnson-mdict-test-render-html ()
  "Renders HTML entry with text properties."
  (johnson-mdict-test--cleanup)
  (let* ((path (johnson-mdict-test--fixture "test-mdict.mdx"))
         (keywords (johnson-mdict--parse-keyword-section path))
         (apple-entry (cl-find "apple" keywords :key #'car :test #'equal))
         (raw (johnson-mdict-retrieve-entry path (cdr apple-entry) 0)))
    (with-temp-buffer
      (johnson-mdict-render-entry raw)
      (let ((text (buffer-substring-no-properties (point-min) (point-max))))
        ;; Tags should be removed.
        (should-not (string-match-p "<b>" text))
        (should (string-match-p "apple" text))
        (should (string-match-p "round fruit" text)))
      ;; Bold face should be applied.
      (let ((pos (text-property-any (point-min) (point-max)
                                    'face 'johnson-bold-face)))
        (should pos)))))

;;;; Index building

(ert-deftest johnson-mdict-test-build-index ()
  "Builds index from MDict fixture."
  (johnson-mdict-test--cleanup)
  (let ((entries nil))
    (johnson-mdict-build-index
     (johnson-mdict-test--fixture "test-mdict.mdx")
     (lambda (hw offset size)
       (push (list hw offset size) entries)))
    (should (= (length entries) 3))
    (let ((headwords (mapcar #'car entries)))
      (should (member "apple" headwords))
      (should (member "cat" headwords))
      (should (member "hello" headwords)))))

;;;; Full integration

(ert-deftest johnson-mdict-test-full-integration ()
  "Full round-trip: detect, parse metadata, build index, retrieve, render."
  (johnson-mdict-test--cleanup)
  (let* ((path (johnson-mdict-test--fixture "test-mdict.mdx")))
    ;; 1. Detect.
    (should (johnson-mdict-detect path))
    ;; 2. Parse metadata.
    (let ((meta (johnson-mdict-parse-metadata path)))
      (should (equal (plist-get meta :name) "Test MDict Dictionary")))
    ;; 3. Build index.
    (let ((entries nil))
      (johnson-mdict-build-index path
                                  (lambda (hw offset size)
                                    (push (list hw offset size) entries)))
      (should (>= (length entries) 3))
      ;; 4. Retrieve and render "apple".
      (let* ((apple-entry (cl-find "apple" entries :key #'car :test #'equal)))
        (should apple-entry)
        (let ((raw (johnson-mdict-retrieve-entry
                    path (nth 1 apple-entry) (nth 2 apple-entry))))
          (with-temp-buffer
            (johnson-mdict-render-entry raw)
            (let ((text (buffer-substring-no-properties
                         (point-min) (point-max))))
              (should (string-match-p "round fruit" text)))))))))

(ert-deftest johnson-mdict-test-full-integration-encrypted ()
  "Full round-trip with encrypted MDict fixture."
  (johnson-mdict-test--cleanup)
  (let* ((path (johnson-mdict-test--fixture "test-mdict-encrypted.mdx"))
         (entries nil))
    (should (johnson-mdict-detect path))
    (johnson-mdict-build-index path
                                (lambda (hw offset size)
                                  (push (list hw offset size) entries)))
    (should (= (length entries) 3))
    (let* ((cat-entry (cl-find "cat" entries :key #'car :test #'equal))
           (raw (johnson-mdict-retrieve-entry
                 path (nth 1 cat-entry) (nth 2 cat-entry))))
      (with-temp-buffer
        (johnson-mdict-render-entry raw)
        (let ((text (buffer-substring-no-properties
                     (point-min) (point-max))))
          (should (string-match-p "feline" text)))))))

;;;; Binary helpers

(ert-deftest johnson-mdict-test-u32be ()
  "Reads 32-bit big-endian integers correctly."
  (let ((data (string #x00 #x00 #x00 #x01)))
    (should (= (johnson-mdict--u32be data 0) 1)))
  (let ((data (string #x00 #x01 #x00 #x00)))
    (should (= (johnson-mdict--u32be data 0) 65536))))

(ert-deftest johnson-mdict-test-u64be ()
  "Reads 64-bit big-endian integers correctly."
  (let ((data (string #x00 #x00 #x00 #x00 #x00 #x00 #x00 #x03)))
    (should (= (johnson-mdict--u64be data 0) 3))))

(ert-deftest johnson-mdict-test-u32le ()
  "Reads 32-bit little-endian integers correctly."
  (let ((data (string #x01 #x00 #x00 #x00)))
    (should (= (johnson-mdict--u32le data 0) 1)))
  (let ((data (string #x00 #x00 #x01 #x00)))
    (should (= (johnson-mdict--u32le data 0) 65536))))

(ert-deftest johnson-mdict-test-adler32 ()
  "Computes Adler-32 checksum correctly."
  ;; Known value: adler32("Wikipedia") = 0x11E60398
  (let ((result (johnson-mdict--adler32
                 (encode-coding-string "Wikipedia" 'utf-8))))
    (should (= result #x11E60398))))

(provide 'johnson-mdict-test)
;;; johnson-mdict-test.el ends here
